"""Action-specific wrapper around visibility-labelled congruence closure."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from algebras import Algebra
from engine import Theory, Term, build_pool, build_signature, const, depth, generate_equations, ns
from visibility_cc import GroundEquation, VisibilityCongruenceClosure, VisibilityRun


def _is_const(t: Term, prefix: str | None = None) -> bool:
    if t.args:
        return False
    return prefix is None or t.head.startswith(prefix + '::')


def classify_equation(l: Term, r: Term, action: str) -> Tuple[str,str]:
    """Best-effort semantic label for an equation generated by engine.py.

    Classification is for explanation only; correctness never depends on it.
    """
    # Native diagrams.
    if l.args and _is_const(r,'A') and l.head.startswith('A::') and all(_is_const(a,'A') for a in l.args):
        return 'CARRIER_TABLE', 'native carrier table'
    if l.args and _is_const(r,'B') and l.head.startswith('B::') and all(_is_const(a,'B') for a in l.args):
        return 'OPERATOR_TABLE', 'native operator table'
    if not l.args and not r.args:
        return 'IDENTIFICATION', 'named-constant identification'

    # Shallow action value rows (Un, Ann, Tab all live here).
    if l.head == action and len(l.args)==2 and _is_const(l.args[0],'B') and _is_const(l.args[1],'A') and _is_const(r,'A'):
        return 'ACTION_VALUE', 'supplied/shallow action value'

    # Carrier compatibility.
    if l.head == action and len(l.args)==2 and _is_const(l.args[0],'B') and l.args[1].head.startswith('A::') and r.head==l.args[1].head:
        return 'COMPATIBILITY', 'carrier compatibility'

    # Transfer bookkeeping.
    if l.head == action and r.head == action and len(l.args)==2 and len(r.args)==2:
        if l.args[0].args and l.args[0].head.startswith('B::') and _is_const(r.args[0],'B') and l.args[1]==r.args[1]:
            return 'TRANSFER', 'transferred operator-table row'

    # Comp: alpha(Bop(g,h),a)=alpha(g,alpha(h,a)).
    if l.head == action and r.head == action and len(l.args)==2 and len(r.args)==2:
        if l.args[0].args and l.args[0].head.startswith('B::') and r.args[1].head==action:
            return 'COMP', 'action composition law'

    # Inv: alpha(Binv(b),alpha(b,a))=a.
    if l.head == action and len(l.args)==2 and l.args[0].args and l.args[0].head.startswith('B::') and l.args[1].head==action and _is_const(r,'A'):
        return 'INV', 'action inverse law'

    # Dist: alpha(Aplus(b1,b2),a)=Aplus(alpha(...),alpha(...)).
    if l.head == action and len(l.args)==2 and l.args[0].args and l.args[0].head.startswith('A::') and r.head.startswith('A::'):
        return 'DIST', 'scalar distributivity law'

    return 'AXIOM', 'ground axiom'


def make_labelled_equations(th: Theory, action: str) -> List[GroundEquation]:
    raw=generate_equations(th,action)
    counts: Dict[str,int]={}
    out=[]
    for l,r in raw:
        kind,base=classify_equation(l,r,action)
        counts[kind]=counts.get(kind,0)+1
        out.append(GroundEquation(l,r,label=f'{base} #{counts[kind]}',kind=kind))
    return out


@dataclass
class ActionVisibilityReport:
    run: VisibilityRun
    action_head: str
    carrier_constants: Tuple[Term,...]
    operator_constants: Tuple[Term,...]
    ground_actions: Tuple[Term,...]
    observed_terms: Tuple[Term,...]
    delta0: int
    delta1: int | None
    eta: int
    action_closed: bool
    closure_horizons: Dict[str,int | None]

    @property
    def fingerprint_h2(self):
        if self.delta1 is None:
            return None
        return (self.delta0, self.delta1-1)

    def carrier_partition(self,D:int):
        return self.run.partition(self.carrier_constants,D)

    def constant_partition(self,D:int):
        return self.run.partition(self.carrier_constants+self.operator_constants,D)


def analyze_action_theory(
    A: Algebra,
    B: Algebra,
    *,
    ident: str='none',
    schemes: Sequence[str]=(),
    merge: bool=False,
    merge_op: str|None=None,
    tab=None,
    target_depth: int=1,
    exact_horizon: int=2,
) -> ActionVisibilityReport:
    th=Theory(A=A,B=B,ident=ident,schemes=tuple(schemes),merge=merge,merge_op=merge_op,tab=tab)
    action,ops,CA,CB=build_signature(th)
    eqs=make_labelled_equations(th,action)
    # Query only the observed layer; deep axiom subterms are pulled in automatically.
    observed=tuple(build_pool(ops,list(CA)+list(CB),target_depth,0))
    ground_actions=tuple(Term(action,(b,a)) for b in CB for a in CA)
    # Ground actions are already in T^1 for a fresh action; under merge they are also depth 1.
    queries=tuple(dict.fromkeys(observed+ground_actions))
    run=VisibilityCongruenceClosure(eqs,queries,horizon=exact_horizon).run()
    constants=tuple(CA+CB)
    delta0=run.stabilization_horizon(constants)
    delta1=run.stabilization_horizon(observed) if target_depth>=1 else None
    eta=run.stabilization_horizon(CA)
    finalD=exact_horizon
    final_carrier_block={}
    snap=run.snapshots[finalD]
    for a in CA:
        final_carrier_block.setdefault(snap[a],[]).append(a)
    carrier_root_ids=set(final_carrier_block)
    closed=True; closure_h={}
    for t in ground_actions:
        h=None
        start=depth(t)
        for D in range(start,finalD+1):
            # class meets a carrier constant at D
            if any(run.same_at(t,a,D) for a in CA):
                h=D;break
        closure_h[t.pretty()]=h
        if h is None:closed=False
    return ActionVisibilityReport(
        run=run,action_head=action,carrier_constants=tuple(CA),operator_constants=tuple(CB),
        ground_actions=ground_actions,observed_terms=observed,delta0=delta0,delta1=delta1,
        eta=eta,action_closed=closed,closure_horizons=closure_h,
    )
